global:
  scrape_interval: 30s
  external_labels:
    demo: sir5kong

## rule_files 从匹配的文件中读取报警规则
rule_files:
  - /etc/prometheus/rules/*

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mysql'
    scrape_interval: 10s
    static_configs:
      - targets: ['mysqldexporter:9104']
        ## labels 自定义标签
        labels:
          db_instance: mysqld-demo
  #- job_name: 'file_sd'
  #  scrape_interval: 60s
  #  file_sd_configs:
  #    - files:
  #      - /etc/prometheus/file_sd/*.yml